name: CI

# åœ¨masteråˆ†æ”¯å‘ç”Ÿpushäº‹ä»¶æ—¶è§¦å‘ã€‚
on:
  push:
    branches:
      - master

env: # è®¾ç½®ç¯å¢ƒå˜é‡
  TZ: Asia/Shanghai # æ—¶åŒºï¼ˆè®¾ç½®æ—¶åŒºå¯ä½¿é¡µé¢ä¸­çš„`æœ€è¿‘æ›´æ–°æ—¶é—´`ä½¿ç”¨æ—¶åŒºæ—¶é—´ï¼‰

jobs:
  build: # è‡ªå®šä¹‰åç§°
    runs-on: ubuntu-latest # è¿è¡Œåœ¨è™šæ‹Ÿæœºç¯å¢ƒubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      # ä½¿ç”¨çš„åŠ¨ä½œã€‚æ ¼å¼ï¼šuserName/repoNameã€‚ä½œç”¨ï¼šæ£€å‡ºä»“åº“ï¼Œè·å–æºç ã€‚ å®˜æ–¹actionsåº“ï¼šhttps://github.com/actions
      - name: Checkout
        uses: actions/checkout@master

      # æŒ‡å®š nodejs ç‰ˆæœ¬
      - name: Use Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # éƒ¨ç½²
      - name: Deploy
        env: # è®¾ç½®ç¯å¢ƒå˜é‡
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: npm install && npm run deploy

      - name: ğŸšš Get latest code
        uses: actions/checkout@gh-pages
      
      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 106.55.157.238 
          username: jimmy
          password: ${{ secrets.ftp_password }}
          server-dir: blog.ichunhui.top/	